### ISSUE TITLE
维度问题

### ISSUE THREAD

**Issue by vincent9619** [bubbliiiing/yolov4-tiny-keras#3]
老师您好,我在训练时出现如下错误, 请问该如何解决?

Traceback (most recent call last):
  File "train.py", line 191, in <module>
    arguments={'anchors': anchors, 'num_classes': num_classes, 'ignore_thresh': 0.5, 'label_smoothing': label_smoothing})(loss_input)
  File "/home/hg100/python3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/hg100/python3.6/lib/python3.6/site-packages/keras/layers/core.py", line 663, in call
    return self.function(inputs, **arguments)
  File "/home/hg100/yolo_train/yolov4-tiny-keras/nets/loss.py", line 163, in yolo_loss
    ciou = box_ciou(pred_box, raw_true_box)
  File "/home/hg100/yolo_train/yolov4-tiny-keras/nets/ious.py", line 28, in box_ciou
    intersect_mins = K.maximum(b1_mins, b2_mins)
  File "/home/hg100/python3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1657, in maximum
    return tf.maximum(x, y)
  File "/home/hg100/python3.6/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5491, in maximum
    "Maximum", x=x, y=y, name=name)
  File "/home/hg100/python3.6/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/hg100/python3.6/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/hg100/python3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/hg100/python3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/home/hg100/python3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 3 and 4 for 'yolo_loss/Maximum' (op: 'Maximum') with input shapes: [?,?,?,3,2], [?,26,26,4,2].

**Comment by bubbliiiing** [comment]
我没有见过，是不是版本问题

**Comment by vincent9619** [comment]
我试了一下您的tiny_tf， 版本完全按照您写的装的，还是出现了一模一样的错误

**Comment by bubbliiiing** [comment]
1.13.2？2.1.5？

**Comment by vincent9619** [comment]
不好意思，我发现哪里错了，是anchor那里我直接把之前普通yolo生成的anchor拿过来用了，原来两个anchor还不一样。抱歉！
